### ISSUE TITLE
Problema con en el archivo InstapagoPayment.php

### ISSUE THREAD

**Issue by matax00** [abr4xas/php-instapago#18]
Buena día amigo, estoy tratando de usar tu código para instapago, estoy siguiendo las instrucciones para usar la libreria.

*Descargue la libreria y la descomprimi.
*Entré con consola en la ruta de la carpeta y ejecute el composer en la misma
*Luego corri el 'composer require instapago/instapago'

Y al intentar ejecutar el comando 'phpunit --configuration="phpunit.xml" --include-path="tests"', la consola me arroja un error : 
>Fatal error: Class 'GuzzleHttp\Client' not found in C:\Users\victor.pellicane\Desktop\php-instapago->master\Instapago\InstapagoGateway\InstapagoPayment.php on line 218

Al dirigirme a dicho archivo  "InstapagoPayment.php"en esa linea (218), me encuentro con lo siguiente:

`$client = new Client([
             'base_uri' => 'https://api.instapago.com/',
             //'debug' => true,`

Estas creando una instancia de un Client.

Al comienzo del mismo archivo en la linea 35 realizas un "use GuzzleHttp\Client as Client;"

Mi pregunta es la siguiente:  que función tiene este "GuzzleHttp", es un namespace que se te olvido incliur? 
Ya que si comento la linea 218 del archivo, se ejecuta el test con el siguiente resultado:

> PHPUnit 5.6.1 by Sebastian Bergmann and contributors.

>ESSS                                                                4 / 4 (100%)

>Time: 47 ms, Memory: 2.25MB

>There was 1 error:

>1) InstapagoPaymentTest::testCreaPago
Undefined variable: client

>C:\Users\victor.pellicane\Desktop\php-instapago-master\Instapago\InstapagoGateway\InstapagoPayment.php:229
>C:\Users\victor.pellicane\Desktop\php-instapago-master\Instapago\InstapagoGateway\InstapagoPayment.php:121
>C:\Users\victor.pellicane\Desktop\php-instapago-master\tests\InstapagoPaymentTest.php:47

>ERRORS!
>Tests: 1, Assertions: 0, Errors: 1, Skipped: 3.

**Comment by matax00** [comment]
Resuelto el problema, solo me faltaba incluir el  guzzlehttp a traves del composer.

Deberías agregar eso en el proceso de instalación.

**Comment by abr4xas** [comment]
@matax00 en el `composer.json` se encuentra requerido guzzle

```json
"require": {
        "php": ">=5.5.0",
        "guzzlehttp/guzzle": "^6.2"
    },
``` 

Cuando haces `composer require instapago/instapago` el automáticamente instala esa dependencia.
